package com.example.navalbattlefinal.controller;

import com.example.navalbattlefinal.view.GameStage;
import com.example.navalbattlefinal.view.WelcomeStage;
import com.example.navalbattlefinal.view.alert.AlertBox;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;

import java.io.IOException;
/** Authors:
 Juliana Melissa Bolaños Araujo-2372224
 Ivan David Ausecha Salamanca-2328223
 Laura Stefania Salazar Blanco-2327896
 Emails:
 juliana.araujo@correounivalle.edu.co
 ivan.ausecha@correounivalle.edu.co
 laura.blanco@coreounivalle.edu.co
 */
/**
 * Controller for the game's welcome screen.
 */
public class WelcomeController {
    /**
     * Method executed when the start button is clicked.
     * @param event Action event generated by the button click.
     * @throws IOException Input/output exception in case of error initializing the game.
     */
    @FXML
    void buttonStart(ActionEvent event) throws IOException {
        GameStage.getInstance().getGameController().inicialize();
        WelcomeStage.deleteInstance();
    }
    /**
     * Method executed when the rules button is clicked.
     * Displays an alert window with the game rules.
     * @param event Action event generated by the button click.
     */
    @FXML
    void buttonRules(ActionEvent event) {
        String title = "¿Como jugar?";
        String header = "Rules";
        String content = "Batalla Naval es un juego de estrategia y suerte para dos participantes (jugador vs computador).\n"+
                "\nEl objetivo del juego es hundir todos los barcos del oponente primero. \n"+
                "\n-> Tablero de posición: Muestra la ubicación de tu flota y los disparos del oponente. Solo es de observación. \n"+
                "\n-> Tablero principal: Muestra el territorio del enemigo donde disparas para hundir sus barcos. Registra tus movimientos, mostrando disparos fallidos y aciertos. \n"+
                "\nCada jugador tiene una flota de 10 barcos:"+
                "\n• 1 portaaviones "+"\n• 2 submarinos "+"\n• 3 destructores "+"\n• 4 fragatas "+
                "\n\nLos barcos se colocan horizontal o verticalmente en el tablero de posición. \n\nTerminología y movimientos: \n"+
                "• Agua: Disparo en una casilla vacía. Se marca con una X y pasa el turno al oponente. "+
                "\n• Tocado: Disparo en una parte de un barco mayor de 1 casilla. Se marca la parte tocada y el jugador vuelve a disparar. "+
                "\n• Hundido: Disparo en una fragata o un barco con todas sus partes tocadas. Se marca el barco completo y el jugador vuelve a disparar. Gana quien hunda toda la flota enemiga.";;
        /**Displays the alert window with the game rules
         **/
        new AlertBox().showMessage(title, header, content);
    }
}
